
nbthread=2

irc.host=irc.twitch.tv
irc.port=6667
irc.login=${irc.login}
irc.pass=${irc.pass}

# rejoindre les channel toutes les 5 minutes
bot.autojoindelai=5

mongo.host=${mongodb.host}
mongo.port=${mongodb.port}
mongo.database=HexasBot